version: '3'

tasks:
  deps:
    desc: "Install project dependencies using Poetry."
    cmds:
      - poetry install --with dev,chat
    sources:
      - pyproject.toml
      - poetry.lock

  run:
    desc: "Run the development server with Uvicorn."
    deps: [deps]
    env:
      ARGO_WATCHER_URL: http://localhost:8080
    cmds:
      - poetry run uvicorn argo_watcher_mcp.app:create_app --factory --host 0.0.0.0 --port 8000 --reload

  bump-patch:
    desc: "Bump the patch version"
    cmds:
      - bump2version patch --allow-dirty

  bump-minor:
    desc: "Bump the minor version"
    cmds:
      - bump2version minor --allow-dirty

  chat:
    desc: "Launch interactive chat with OpenAI"
    cmds:
      - ./scripts/ai-chat.py
    requires:
      vars: [OPENAI_API_KEY]
