name: Build and Publish

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ghcr.io/shini4i/argo-watcher-mcp:latest
            ghcr.io/shini4i/argo-watcher-mcp:${{ github.ref_name }}
          push: true
